vscode:
  extensions:
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==

tasks:
  - init: |
      ln -s $(pwd)/.gitpod/.theia .
      mkdir build && cd build
      cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      make -j $(nproc)
